name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./ai모형관리/pom.xml
          mvn clean package -f ./데이터시각화관리/pom.xml
          mvn clean package -f ./데이터관리/pom.xml
          mvn clean package -f ./통계관리/pom.xml
          mvn clean package -f ./ai요약관리/pom.xml
          mvn clean package -f ./대시보드/pom.xml

      - name: Docker Build and push for Ai모형관리
        uses: docker/build-push-action@v4
        with:
          context: ./ai모형관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ai모형관리:latest
            ghcr.io/${{ github.repository }}/ai모형관리:${{ github.ref_name }}
            
      - name: Docker Build and push for 데이터시각화관리
        uses: docker/build-push-action@v4
        with:
          context: ./데이터시각화관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/데이터시각화관리:latest
            ghcr.io/${{ github.repository }}/데이터시각화관리:${{ github.ref_name }}
            
      - name: Docker Build and push for 데이터관리
        uses: docker/build-push-action@v4
        with:
          context: ./데이터관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/데이터관리:latest
            ghcr.io/${{ github.repository }}/데이터관리:${{ github.ref_name }}
            
      - name: Docker Build and push for 통계관리
        uses: docker/build-push-action@v4
        with:
          context: ./통계관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/통계관리:latest
            ghcr.io/${{ github.repository }}/통계관리:${{ github.ref_name }}
            
      - name: Docker Build and push for Ai요약관리
        uses: docker/build-push-action@v4
        with:
          context: ./ai요약관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ai요약관리:latest
            ghcr.io/${{ github.repository }}/ai요약관리:${{ github.ref_name }}
            
      - name: Docker Build and push for 대시보드
        uses: docker/build-push-action@v4
        with:
          context: ./대시보드
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/대시보드:latest
            ghcr.io/${{ github.repository }}/대시보드:${{ github.ref_name }}
            
