server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: ai모형관리
          uri: http://localhost:8082
          predicates:
            - Path=/ai모형/**, 
        - id: 데이터시각화관리
          uri: http://localhost:8083
          predicates:
            - Path=/시각화지도/**, 
        - id: 데이터관리
          uri: http://localhost:8084
          predicates:
            - Path=/데이터집합/**, /분석결과집합/**, 
        - id: 통계관리
          uri: http://localhost:8085
          predicates:
            - Path=/통계관리/**, 
        - id: ai요약관리
          uri: http://localhost:8086
          predicates:
            - Path=/ai요약/**, 
        - id: 대시보드
          uri: http://localhost:8087
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: ai모형관리
          uri: http://ai모형관리:8080
          predicates:
            - Path=/ai모형/**, 
        - id: 데이터시각화관리
          uri: http://데이터시각화관리:8080
          predicates:
            - Path=/시각화지도/**, 
        - id: 데이터관리
          uri: http://데이터관리:8080
          predicates:
            - Path=/데이터집합/**, /분석결과집합/**, 
        - id: 통계관리
          uri: http://통계관리:8080
          predicates:
            - Path=/통계관리/**, 
        - id: ai요약관리
          uri: http://ai요약관리:8080
          predicates:
            - Path=/ai요약/**, 
        - id: 대시보드
          uri: http://대시보드:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
