---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai모형관리
  labels:
    app: ai모형관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai모형관리
  template:
    metadata:
      labels:
        app: ai모형관리
    spec:
      containers:
        - name: ai모형관리
          image: username/ai모형관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 데이터시각화관리
  labels:
    app: 데이터시각화관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 데이터시각화관리
  template:
    metadata:
      labels:
        app: 데이터시각화관리
    spec:
      containers:
        - name: 데이터시각화관리
          image: username/데이터시각화관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 데이터관리
  labels:
    app: 데이터관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 데이터관리
  template:
    metadata:
      labels:
        app: 데이터관리
    spec:
      containers:
        - name: 데이터관리
          image: username/데이터관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 통계관리
  labels:
    app: 통계관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 통계관리
  template:
    metadata:
      labels:
        app: 통계관리
    spec:
      containers:
        - name: 통계관리
          image: username/통계관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai요약관리
  labels:
    app: ai요약관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai요약관리
  template:
    metadata:
      labels:
        app: ai요약관리
    spec:
      containers:
        - name: ai요약관리
          image: username/ai요약관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 대시보드
  labels:
    app: 대시보드
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 대시보드
  template:
    metadata:
      labels:
        app: 대시보드
    spec:
      containers:
        - name: 대시보드
          image: username/대시보드:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ai모형관리
  labels:
    app: ai모형관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ai모형관리


---


apiVersion: v1
kind: Service
metadata:
  name: 데이터시각화관리
  labels:
    app: 데이터시각화관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 데이터시각화관리


---


apiVersion: v1
kind: Service
metadata:
  name: 데이터관리
  labels:
    app: 데이터관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 데이터관리


---


apiVersion: v1
kind: Service
metadata:
  name: 통계관리
  labels:
    app: 통계관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 통계관리


---


apiVersion: v1
kind: Service
metadata:
  name: ai요약관리
  labels:
    app: ai요약관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ai요약관리


---


apiVersion: v1
kind: Service
metadata:
  name: 대시보드
  labels:
    app: 대시보드
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 대시보드

